[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa ubuntu@111.88.248.183"'
ansible_python_interpreter=/usr/bin/python3

[bastion_hosts]
bastion ansible_host=111.88.248.183 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[web_hosts]
web1 ansible_host=10.2.0.28
web2 ansible_host=10.3.0.12

[zabbix_hosts]
zabbix ansible_host=84.252.129.249 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[elasticsearch_hosts]
elasticsearch ansible_host=10.4.0.17

[kibana_hosts]
kibana ansible_host=111.88.249.107 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[nginx:children]
web_hosts

[zabbix_server:children]
zabbix_hosts

[zabbix_agent:children]
web_hosts
zabbix_hosts

[elastic_stack:children]
elasticsearch_hosts
kibana_hosts
